### ISSUE TITLE
ManagedConcourseServerTest should use latest code

### ISSUE THREAD

**Issue by jtnelson** [cinchapi/concourse#176]
In the `starting` method of the TestWatcher, change the impl to this

``` java
server = ManagedConcourseServer.manageNewServer(new File(ConcourseCodebase.cloneFromGithub().buildInstaller()));
```

NOTE: I tried this already but it seems like there are some issues with the server stopping. Need to investigate.

**Comment by mtbar131** [comment]
Hi, 

I am new to concourse and I would like to start contributing to concourse. 

I have tried the above code change and I did not get any exceptions. Can you please provide little more details on this so that I can start working on this. 

Also I am beginner in open source contributions so any specific guidance will be very helpful.
